a = input("Enter a number: ")
b = input("Enter a number: ")
a=int (a)
b=int (b)
sum = (a + b)
mul = (a * b)
frac = (a / b)
sub = (a - b)
qout = (a // b)
rem = (a % b)
print("Sum of", a ,"&",b,  "is ", sum)
print("Multiplication of ", a , "&", b, "is ", mul)
print("Fraction of ", a, "&", b ,"is ", frac)
print("Subtraction of ", a ,"&",b, "is ", sub)
print("Qoutient of ", a ,"& ",b, "is ", qout)
print("Remainder of ", a, "& ",b, "is ", rem)